---
#apiVersion: v1
#kind: Service
#metadata:
#  annotations:
#    kubernetes.io/ingress.class: "traefik"
#    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
#    traefik.ingress.kubernetes.io/redirect-entry-point: https
#  name: raindrop
#  labels:
#    app: raindrop
#spec:
#  ports:
#    - port: 8080
#      protocol: TCP
#  selector:
#    app: raindrop

apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  #type: "{{ .Values.back_type }}"
  clusterIP: None
  ports:
    - port: 8080
      targetPort: http
  selector:
    app: backend-chart

